from app.models import db, Recipe


# Adds a demo location, you can add other locations here if you want

def seed_recipes():

    db.session.bulk_insert_mappings(Recipe,
                                    [
                                        {
                                            "description": "Creamy tomato bisque made with sundried tomatoes. If there are no fresh tomatoes at hand, use canned. The soup is delicious and silky if you thicken it with tapioca.",
                                            "title": "Alouette Sundried Tomato and Basil Bisque",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 34.82,
                                            "servings": 8,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/632250-556x370.jpg"
                                        },
                                        {
                                            "description": "Toasted Agnolotti is breaded deep-fried ravioli, usually served as an appetizer. It was created and popularized in St. Louis, Missouri at two restaurants, Mama Campisi's and Charlie Gitto's. Both are located in an Italian-American neighborhood, The Hill.",
                                            "title": "Toasted Agnolotti (or Ravioli)",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 195.19,
                                            "servings": 2,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/631807-556x370.jpg"
                                        },
                                        {
                                            "description": "Once you learn how to make cheese rounds that you can customize--and then freeze for up to three months--you'll never host a party without them! Depending on which cheese seasoning you choose, this make-ahead round recipe can fit any season or color palette.",
                                            "title": "Easy Onion Cheese Rounds",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 24.75,
                                            "servings": 8,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/642041-556x370.jpg"
                                        },
                                        {
                                            "description": "This easy Black Bean Tacos recipe is simple and fuss-free to prepare, yet packed with bold flavor! Made with convenient canned black beans, fresh vegetables, savory seasonings and a sweet corn salsa, these tacos are filled with hearty, yet wholesome ingredients! These healthy tacos may be vegetarian, but you won’t miss the meat at all!",
                                            "title": "Black Bean and Peppers Taco Filling",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 54.61,
                                            "servings": 8,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/635058-556x370.jpg"
                                        },
                                        {
                                            "description": "Admittedly, this salad may be trying a little too hard (or perhaps I’ve been watching too much Top Chef).  In any case, if you’re looking for a sophisticated, unique way to start off a dinner party, this is just the trick.  The key to this dish is balance.  Endive is naturally very bitter, but is offset by drizzling honey over the whole plate.  The figs and pistachios add texture, and the fried prosciutto… well, who doesn’t love crispy pork?",
                                            "title": "Roasted Endive Salad With Prosciutto, Figs and Pistachios",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 363.51,
                                            "servings": 4,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/658579-556x370.jpg"
                                        },
                                        {
                                            "description": "Who needs boring ol’ pie crust when you have pizza crust, right? For this holiday inspired recipe I used Mama Mary’s Original Mini Pizza Crust to make a Pumpkin Pecan Pie Dessert Pizza that is easy to make and the perfect size for a fun dessert at home!",
                                            "title": "Pecan Pumpkin Pie Dessert Pizza with Maple Whipped Cream",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 140.59,
                                            "servings": 10,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/655525-556x370.jpg"
                                        },
                                        {
                                            "description": "Classic caesar salad using crisp romaine lettuce and tossed with a creamy homemade dressing. Briny salt-cured anchovies add the characteristic flavor while eggs create the perfect emulsion for the dressing. Just top with aged Parmesan cheese and crunchy croutons!",
                                            "title": "Classic Caesar Salad",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 612.16,
                                            "servings": 1,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/631890-556x370.jpg"
                                        },
                                        {
                                            "description": "Lemongrass, a long, fibrous, grayish green grass with a paler bulblike base and a mild lemon fragrance, is a staple herb of Southeast Asia, where it is used to flavor soups, curry pastes and other preparations. To use it, peel away any dry leaves from the base and trim off the grassy top section. To maximize the citrus flavor, crush the base and stem with the flat side of a chef's knife or cleaver before slicing or using. If using lemongrass in large pieces, remove it before serving the dish.",
                                            "title": "Shrimp and Lemongrass Soup",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 168.22,
                                            "servings": 4,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/659934-556x370.jpg"
                                        },
                                        {
                                            "description": "Four-Berry Blast Fruit Smoothie are a refreshing and delicious way to enjoy a hot summer day. These smoothies are full of yummy berry flavor and a cinch to make!",
                                            "title": "Four-Berry Blast Fruit Smoothie",
                                            "vegetarian": True,
                                            "time": 10,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 123.98,
                                            "servings": 4,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/643241-556x370.jpg"
                                        },
                                        {
                                            "description": "This Mediterranean-inspired relish pairs nicely with most grilled fish, so if tuna isn’t your favorite, substitute salmon, halibut, or swordfish steaks. For a shortcut, pulse the tomatoes and olives a few times in a food processor and then add the remaining ingredients and pulse to combine.",
                                            "title": "Grilled Fish With Sun Dried Tomato Relish",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 889.37,
                                            "servings": 2,
                                            "userId": 2,
                                            "image": "https://spoonacular.com/recipeImages/645714-556x370.jpg"
                                        },
                                        {
                                            "description": "This healthy summer dinner subs zoodles for pasta to help use up your zucchini bounty--as well as slash calories and carbs. Once the spiralized zucchini has time to soak up the herby pesto sauce, this chicken and pesto pasta makes particularly good leftovers.",
                                            "title": "Pesto Chicken Zoodles",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 274.6,
                                            "servings": 3,
                                            "userId": 3,
                                            "image": "https://spoonacular.com/recipeImages/780001-556x370.jpg"
                                        },
                                        {
                                            "description": "Crispy Tiger Prawns With Honey and Garlic Sauce elies on the freshest-quality seafood, and , for the sauce, I always try to buy fresh, Australian-grown garlic rather than the lower-quality imported product, which I find leaves too strong an artificial garlicky taste and smell, well after the meal is over. Make sure your deep-frying oil is clean and at the right temperature. Freeze the prawn heads and reserve for stock.",
                                            "title": "Crispy Tiger Prawns With Honey and Garlic Sauce",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 116.12,
                                            "servings": 3,
                                            "userId": 3,
                                            "image": "https://spoonacular.com/recipeImages/640844-556x370.jpg"
                                        },
                                        {
                                            "description": "The French technique of cooking “in paper” gently steams your protein and veggies in liquid—wine, in this case—so barely any cooking fat is necessary. Our other favorite part? How easy it is to pack a ton of veggies into this one-dish wonder with minimal prep work or clean up.",
                                            "title": "Chicken En Papillote With Basil and Cherry Tomatoes",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 262.25,
                                            "servings": 1,
                                            "userId": 3,
                                            "image": "https://spoonacular.com/recipeImages/638071-556x370.jpg"
                                        },
                                        {
                                            "description": "These buttermilk onion rings are briefly soaked in buttermilk and double-dipped in flour before frying to ensure an extra crisp coating and oh so tender onions within. Spectacular alongside burgers. Or simply on their own.",
                                            "title": "Buttermilk Onion Rings",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 224.72,
                                            "servings": 3,
                                            "userId": 3,
                                            "image": "https://spoonacular.com/recipeImages/636558-556x370.jpg"
                                        },
                                        {
                                            "description": "This Ham with Orange Rosemary Marmalade Glaze is the easiest and most delicious way to impart flavor and sweetness into an ordinary ham.",
                                            "title": "Ham with Orange Rosemary Marmalade Glaze",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 489.7,
                                            "servings": 4,
                                            "userId": 3,
                                            "image": "https://spoonacular.com/recipeImages/646217-556x370.jpg"
                                        },
                                        {
                                            "description": "Tasty, tasty, tasty little Asian meatballs with a delectable sweet (and kicky) chili sauce. Serve over brown rice or quinoa for a healthy, easy meal! ",
                                            "title": "Asian Sweet Chili Chicken Meatballs",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 137.32,
                                            "servings": 6,
                                            "userId": 4,
                                            "image": "https://spoonacular.com/recipeImages/803061-556x370.jpg"
                                        },
                                        {
                                            "description": "This garden-fresh strawberry basil sorbet provides a delicious twist on classic, sweet strawberry sorbet. It’s equally welcome as a warm afternoon refreshment or a shocking palate cleanser in the dead of winter. To ensure a fresh from the berry patch flavor, make sure to use fresh berries for this recipes, as frozen strawberries are often lacking in flavor.",
                                            "title": "Strawberry Basil Sorbet",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 76.94,
                                            "servings": 1,
                                            "userId": 4,
                                            "image": "https://spoonacular.com/recipeImages/716424-556x370.jpg"
                                        },
                                        {
                                            "description": "Moroccan Chickpean and Lentil stew (Harira) is a comforting Moroccan soup that features chickpeas, lentils, and plenty of deep flavors from harissa paste and toasted spices. Typically, Harira soup includes ground meat, but this easy version is vegetarian (and vegan) friendly! Even better– it mostly makes use of pantry staples, so it’s easy to stock up ahead of time and make this delicious soup whenever the craving hits.",
                                            "title": "Moroccan Chickpea and Lentil Stew (Harira)",
                                            "vegetarian": True,
                                            "time": 30,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 126.12,
                                            "servings": 3,
                                            "userId": 4,
                                            "image": "https://spoonacular.com/recipeImages/652417-556x370.jpg"
                                        },
                                        {
                                            "description": "This simple-to-make, hearty appetizer features goat cheese and wild mushrooms atop crisp baguette rounds.",
                                            "title": "Rustic Brie Toasts with Wild Mushroom, Cranberry and Shallot",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 66.25,
                                            "servings": 10,
                                            "userId": 4,
                                            "image": "https://spoonacular.com/recipeImages/658914-556x370.jpg"
                                        },
                                        {
                                            "description": "Made with a delicious cream cheese filling, This dish is really going to impress your family and friends this holiday season.",
                                            "title": "Apple & Cream Cheese Braid",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 1036.55,
                                            "servings": 1,
                                            "userId": 4,
                                            "image": "https://spoonacular.com/recipeImages/632452-556x370.jpg"
                                        },
                                        {
                                            "description": "Deep fried gluten-free onion rings are a real treat! Use this recipe and either Vidalia or Walla Walla onions; they're crunchy delicious. Make some the next time your cooking on the grill or instead of going out for fast food.",
                                            "title": "Gluten Free Onion Rings",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 83.07,
                                            "servings": 4,
                                            "userId": 4,
                                            "image": "https://spoonacular.com/recipeImages/644846-556x370.jpg"
                                        },
                                        {
                                            "description": "Get in the holiday spirit with some honey roasted cranberries.  Drizzle these on top of a creamy bed of orange flecked ricotta cheese on a crispy baguette and you’ll have a festive crostini appetizer for any party!",
                                            "title": "Roasted Cranberries, Ricotta & Honey Crostini",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 84.04,
                                            "servings": 1,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/716412-556x370.jpg"
                                        },
                                        {
                                            "description": "This version of paella uses accessible ingredients, standard kitchen equipment, and a simple presentation. And you know, it’s a better dish because of it! Spain’s classic rice dish, paella [pie-AY-yuh], has great flavor and eye appeal. But today’s cooks might be inclined to pass it by. Made in a special pan with homemade stock and meticulous presentation, it’s just too fussy. Isn’t there an easier path to paella? Yes, there is! This recipe proves that using everyday ingredients and cooking equipment still results in a terrific dish. Instead of buying a paella pan (a wide, shallow skillet), use a sauté pan. And rather than making chicken stock, “doctor up” store-bought broth with shrimp shells, bay leaves, and saffron. This one simple step gives you an intensely flavored broth that really punches up the paella’s taste. While the rice may be the star of paella, it’s the chicken, shrimp, and kielbasa that fill you up and complete the meal. ",
                                            "title": "Chicken, Kielbasa and Shrimp Paella",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 238.13,
                                            "servings": 8,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/641911-556x370.jpg"
                                        },
                                        {
                                            "description": "Coconut Macaroons With Chocolate Drizzle are chewy on the inside and golden brown on the outside with just enough chocolate to make everything extra delicious.",
                                            "title": "Coconut Macaroons With Chocolate Drizzle",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 27.23,
                                            "servings": 24,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/639779-556x370.jpg"
                                        },
                                        {
                                            "description": "These Hawaiian Baked Beans are sweet and salty with bits of ham throughout!. A great side for luaus or BBQs. ",
                                            "title": "Hawaiian Baked Beans",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 161.29,
                                            "servings": 8,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/634545-556x370.jpg"
                                        },
                                        {
                                            "description": "These Easy Baked Pork Chops only require a few spices to really make them stand out. They are juicy, tender, and full of flavor.",
                                            "title": "Baked Pork Chop",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 318.81,
                                            "servings": 3,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/715481-556x370.jpg"
                                        },
                                        {
                                            "description": "This Crunchy Lemon Almond and Coconut Granola is pretty much my new favorite thing. With it’s perfectly toasted oats, light lemon flavor, crunchy almonds and chia seeds, plus a hint of coconut, it’s got a lot going for it!",
                                            "title": "Lemon Coconut Granola",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 56.12,
                                            "servings": 15,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/649567-556x370.jpg"
                                        },
                                        {
                                            "description": "This Roasted Cabbage Wedge Salad encourages you to skip the iceberg lettuce and make your next wedge salad with cabbage. Roasting it adds extra flavor!",
                                            "title": "Roasted Cabbage Wedge Salad with Yogurt Gorgonzola Dressing",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 129.8,
                                            "servings": 4,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/716430-556x370.jpg"
                                        },
                                        {
                                            "description": "A wonderful baked chicken recipe that's quick and easy! Using just a few handy ingredients, create a delicious main dish, that also makes great leftovers - if there are any! Serve with a salad and pasta or rice for a quick, scrumptious dinner.",
                                            "title": "Baked Parmesan Chicken",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 351.25,
                                            "servings": 4,
                                            "userId": 6,
                                            "image": "https://spoonacular.com/recipeImages/641836-556x370.jpg"
                                        },
                                        {
                                            "description": "These Red Velvet Brownies are such a divine holiday treat! They’re so amazing in flavour, and the vegan cream cheese frosting on top is the perfect final touch!",
                                            "title": "Vegan Red Velvet Brownies",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 41.99,
                                            "servings": 8,
                                            "userId": 6,
                                            "image": "https://spoonacular.com/recipeImages/646524-556x370.jpg"
                                        },
                                        {
                                            "description": "In Denmark, this meringue-like ice cream topping called guf. It is really easy to make, and it tastes divine. The guf you get at the ice cream shops in Denmark is often pink and tastes like strawberry. You can get the same flavor by adding a spoonful of strawberry jam, but if you want a very pink color, you will need a few drops of food coloring",
                                            "title": "Guf Danish Ice Cream Topping",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 39.5,
                                            "servings": 4,
                                            "userId": 6,
                                            "image": "https://spoonacular.com/recipeImages/631781-556x370.jpg"
                                        },
                                        {
                                            "description": "Here is a nod both to the original bananas Foster at Brennan’s restaurant in the French Quarter of New Orleans and to the luxe version of bananas baba au rhum that the Louisiana chef Allison Vines-Rushing once cooked at Jack’s Luxury Oyster Bar in the East Village. Silky and rich, deep with the flavors of bananas, rum and custard, it is not much work to make, and pays off in incredible flavor. Do not be afraid to use an even darker sugar than the brown called for in the recipe, though molasses may be a step too far. You are looking for a deep caramel hue and flavor in the sauce, to complement the rum and the fruit. ",
                                            "title": "Banana Foster Bread Pudding",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 174.61,
                                            "servings": 8,
                                            "userId": 7,
                                            "image": "https://spoonacular.com/recipeImages/634091-556x370.jpg"
                                        },
                                        {
                                            "description": "Some say beans and rice is the most nutritious and well balanced meal in the world! Try adding your favorite chutney or salsa to this dish when you serve it!",
                                            "title": "Homemade Rice and Beans",
                                            "vegetarian": True,
                                            "time": 35,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 106.02,
                                            "servings": 2,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/716627-556x370.jpg"
                                        },
                                        {
                                            "description": "Valentine's Chicken Marsala is an Italian-American dish of golden pan-fried chicken cutlets and mushrooms in a rich Marsala wine sauce. Though it’s a classic restaurant dish, it’s really easy to make at home. ",
                                            "title": "Valentine's Chicken Marsala",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 271.68,
                                            "servings": 3,
                                            "userId": 5,
                                            "image": "https://spoonacular.com/recipeImages/664270-556x370.jpg"
                                        },
                                        {
                                            "description": "Crispy, Delicious Popcorn Chicken Is A Family Favorite!! Not Only Is It Easy To Make But It’s A Hit With The Entire Family Making Dinner A Cinch!",
                                            "title": "Popcorn Chicken",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 158.71,
                                            "servings": 2,
                                            "userId": 7,
                                            "image": "https://spoonacular.com/recipeImages/716358-556x370.jpg"
                                        },
                                        {
                                            "description": "Taking the dairy out of this vegan Paneer Butter Masala, a Punjabi classic, does not take away from its mindblowing flavor or its authenticity or its deliciousness. Give this gluten-free recipe a try and you'll be hooked for good.",
                                            "title": "Paneer Makhani",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 205.38,
                                            "servings": 4,
                                            "userId": 7,
                                            "image": "https://spoonacular.com/recipeImages/654534-556x370.jpg"
                                        },
                                        {
                                            "description": "Homemade Crepes made with strawberry cheesecake filling are perfect for any occasion. These chocolate crepes are easy to make with a crepe pan or an omelet pan. Your entire family will enjoy this mouthwatering breakfast, and you won’t believe just how easy it is to make this chocolate crepes recipe.",
                                            "title": "Strawberry Cheesecake Chocolate Crepes",
                                            "vegetarian": True,
                                            "time": 40,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 168.57,
                                            "servings": 4,
                                            "userId": 7,
                                            "image": "https://spoonacular.com/recipeImages/715569-556x370.jpg"
                                        },
                                        {
                                            "description": "Turn plain pierogies into a magnificent meal! ",
                                            "title": "Pierogi Casserole",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 155.09,
                                            "servings": 4,
                                            "userId": 7,
                                            "image": "https://spoonacular.com/recipeImages/715563-556x370.jpg"
                                        },
                                        {
                                            "description": "A lovely fusion of sweet and sour pink lemonade baked into a soft and chewy cookie covered in picturesque crinkles and velvety powdered sugar; easy and refreshingly summer.",
                                            "title": "Pink Lemonade Crinkle Cookies",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 53.93,
                                            "servings": 5,
                                            "userId": 8,
                                            "image": "https://spoonacular.com/recipeImages/715541-556x370.jpg"
                                        },
                                        {
                                            "description": "The rice is cooked in a flavorful tomato and pepper purée; his version is vegan, and laced with chile heat. ",
                                            "title": "Jollof Rice",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 122.98,
                                            "servings": 3,
                                            "userId": 9,
                                            "image": "https://spoonacular.com/recipeImages/716298-556x370.jpg"
                                        },
                                        {
                                            "description": "Mini chocolate coffins embellished with royal-icing flourishes offer a suitably final dessert course for any Halloween feast. ",
                                            "title": "Brownie Coffins",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 55.55,
                                            "servings": 5,
                                            "userId": 10,
                                            "image": "https://spoonacular.com/recipeImages/636328-556x370.jpg"
                                        },
                                        {
                                            "description": "This fish is extremely flavorful and fiery with a kick of Cajun tartar sauce. Spice up your mundane meal plan and serve this gluten-free dinner on a weeknight. It's so easy to make!",
                                            "title": "Cornmeal-Crusted Catfish with Cajun Seasoning and Spicy Tartar Sauce",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 287.28,
                                            "servings": 4,
                                            "userId": 10,
                                            "image": "https://spoonacular.com/recipeImages/640166-556x370.jpg"
                                        },
                                        {
                                            "description": "Bacon Wrapped Pork Tenderloin is such an easy meal to prepare and serve!  Seasoned pork tenderloin is wrapped with bacon slices and baked, or grilled, to perfection!",
                                            "title": "Bacon Wrapped Pork Tenderloin",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 257.42,
                                            "servings": 4,
                                            "userId": 7,
                                            "image": "https://spoonacular.com/recipeImages/633344-556x370.jpg"
                                        },
                                        {
                                            "description": "Naturally gluten free and vegan, you'll love the flavors of coffee and chai in this recipe",
                                            "title": "Vegan Dirty Chai Pudding",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 193.28,
                                            "servings": 6,
                                            "userId": 8,
                                            "image": "https://spoonacular.com/recipeImages/664429-556x370.jpg"
                                        },
                                        {
                                            "description": "Ratatouille is a classic end-of-summer French stew that’s fun to say (rat-tuh-TOO-ee) and fun to make. It’s packed with fresh produce: tomatoes, eggplant, zucchini and yellow squash, and bell pepper.",
                                            "title": "Ratatouille With Brie",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 196.79,
                                            "servings": 4,
                                            "userId": 8,
                                            "image": "https://spoonacular.com/recipeImages/657939-556x370.jpg"
                                        },
                                        {
                                            "description": "This peri peri chicken recipe smothers chicken in a homemade peri peri sauce then bakes or grills them and serves them with extra sauce. It’s a quick and easy weeknight meal. ",
                                            "title": "Peri Peri Chicken and Savoury Rice",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 143.05,
                                            "servings": 6,
                                            "userId": 8,
                                            "image": "https://spoonacular.com/recipeImages/716296-556x370.jpg"
                                        },
                                        {
                                            "description": "Cheddar dill scones are a savory quick bread that creates an irresistible aroma.",
                                            "title": "Savory Cheese Dill Scones",
                                            "vegetarian": True,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 29.57,
                                            "servings": 12,
                                            "userId": 8,
                                            "image": "https://spoonacular.com/recipeImages/659463-556x370.jpg"
                                        },
                                        {
                                            "description": "A delivious family recipe, it is great to serve with bulgur and a sauté of zucchini and summer squash",
                                            "title": "Steak with Lemon and Capers",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": False,
                                            "pricePerServing": 646.43,
                                            "servings": 2,
                                            "userId": 10,
                                            "image": "https://spoonacular.com/recipeImages/661531-556x370.jpg"
                                        },
                                        {
                                            "description": "These baked African style chicken satay are smothered in a spicy, flavorful peanut butter sauce. Perfect for snacks, summer picnic or as main dish. Amazingly good!",
                                            "title": "Chicken Suya",
                                            "vegetarian": False,
                                            "time": 45,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 186.02,
                                            "servings": 1,
                                            "userId": 10,
                                            "image": "https://spoonacular.com/recipeImages/716342-556x370.jpg"
                                        },
                                        {
                                            "description": "Jambalaya is a hallmark of the Creole cuisine. It is a versatile dish that combines cooked rice with a variety of ingredients that can include tomatoes, onion, green peppers and almost any kind of meat, poultry or shellfish. The dish varies widely from cook to cook. Some think the name derives from the French word jambon, meaning ham, the main ingredient in many of the first jambalayas. Rice is a staple in many Creole dishes. ",
                                            "title": "Chicken and Sausage Jambalaya",
                                            "vegetarian": False,
                                            "time": 75,
                                            "cheap": False,
                                            "glutenfree": True,
                                            "pricePerServing": 188.06,
                                            "servings": 8,
                                            "userId": 10,
                                            "image": "https://spoonacular.com/recipeImages/715545-556x370.jpg"
                                        }
                                    ]
                        )
    db.session.commit()

# Uses a raw SQL query to TRUNCATE the locations table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and resets
# the auto incrementing primary key


def undo_recipes():
    db.session.execute('TRUNCATE recipes;')
    db.session.commit()
